/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    ListDemos: typeof import('./src/components/ListDemos.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
    WrapperDemo: typeof import('./src/components/WrapperDemo.vue')['default']
  }
}
